### ISSUE TITLE
No longer compiles in ESPHome 2024.5.0

### ISSUE THREAD

**Issue by patfelst** [Pionizer/pionizer-axp192#1]
As per the title, this has been working for a long time for me, but no longer compiles. I get this error:
```c++
Compiling .pioenvs/co2-workshop-core2/src/main.cpp.o
/config/esphome/co2-workshop-core2.yaml: In lambda function:
/config/esphome/co2-workshop-core2.yaml:17:7: error: 'axp192_axp192component' was not declared in this scope
       - lambda: "axp192_axp192component->set_brightness(0.5);"
```
My config is:
```yaml
external_components:
  - source: github://Pionizer/pionizer-axp192
    components: [axp192]
    refresh: 1days

binary_sensor:
  - platform: homeassistant
    internal: true
    id: presence
    entity_id: light.led_strip_workshop_shelf_dimmer
    on_press: 
      - lambda: "axp192_axp192component->set_brightness(1.0);"
    on_release:
      - lambda: "axp192_axp192component->set_brightness(0.5);"

sensor:
  - platform: axp192
    model: M5CORE2
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    brightness: 100%
    battery_level:
      name: "Battery Level"
      id: batterylevel
```
any ideas what might be wrong?

**Comment by patfelst** [comment]
Apologies, somebody on discord answered my question. It seems I should have added an ID to the sensor, e.g.
```yaml
sensor:
  - platform: axp192
    id: axp192_id
    model: M5CORE2
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    brightness: 100%
    battery_level:
      name: "Battery Level"
      id: batterylevel
```
and then set the brightness like this
```yaml
id(axp192_id).set_brightness(1.0);
```
This works for me so I'll close this.
